server:
  port: 8761
# -- Eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 5000 # 인스턴스 제거 간격(5초)
    renewal-percent-threshold: 0.85 # 갱신 임계값 조정

spring:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  cloud:
    config:
      enabled: false

management:
  tracing:
    sampling:
      probability: 1.0 # 0.0 ~ 1.0 사이 값 (모든 요청을 트레이싱하려면 1.0)
logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]" # 로그에 traceId, spanId 추가