server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://localhost:13307/post?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  cloud:
    config:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0 # 0.0 ~ 1.0 사이 값 (모든 요청을 트레이싱하려면 1.0)
logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]" # 로그에 traceId, spanId 추가